=== luoyexiaohe/MyTest/config/hfyReverse.dtd
<?xml version="1.0" encoding="UTF-8">
<!ELEMENT class (import*,class-qualifier,class-father,interfaces*,attribute,methond)>
<!ELEMENT import(import-class*)>
<!ELEMENT import-class (#PCDATA)>
<!ELEMENT class-qualifier (#PCDATA)>
<!ELEMENT class-father (#PCDATA)>
<!ELEMENT interfaces (interface*)>
<!ELEMENT interface (#PCDATA)
<!ELEMENT attribute(#PCDATA)>
<!ELEMENT methond(#PCDATA)>

=== luoyexiaohe/MyTest/config/DataSource/DataSource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class SYSTEM "../hfyReverse.dtd">
<class>
    <import>
        <import-class>DataSource.DataSource.DataSource</import-class>
    </import>
<!--<class-name>Test</class-name> -->
    <class-qualifier>public</class-qualifier>     
    <class-father></class-father>
    <interfaces>
        <interface>interface1</interface>
    </interfaces>
    <attribute qualifier="private" isStatic="false" isFinal="false"/>
    <methond qualifier="public" isStatic="false" isFinal="false"/>
</class>
